// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.0--rc1
// source: director.proto

package Director

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensaje de Mercenario a Director (1)
type Merc_Dir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre   string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Piso     int32  `protobuf:"varint,2,opt,name=piso,proto3" json:"piso,omitempty"`
	Decision int32  `protobuf:"varint,3,opt,name=decision,proto3" json:"decision,omitempty"`
	Vivo     bool   `protobuf:"varint,4,opt,name=vivo,proto3" json:"vivo,omitempty"`
}

func (x *Merc_Dir) Reset() {
	*x = Merc_Dir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_director_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Merc_Dir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Merc_Dir) ProtoMessage() {}

func (x *Merc_Dir) ProtoReflect() protoreflect.Message {
	mi := &file_director_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Merc_Dir.ProtoReflect.Descriptor instead.
func (*Merc_Dir) Descriptor() ([]byte, []int) {
	return file_director_proto_rawDescGZIP(), []int{0}
}

func (x *Merc_Dir) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Merc_Dir) GetPiso() int32 {
	if x != nil {
		return x.Piso
	}
	return 0
}

func (x *Merc_Dir) GetDecision() int32 {
	if x != nil {
		return x.Decision
	}
	return 0
}

func (x *Merc_Dir) GetVivo() bool {
	if x != nil {
		return x.Vivo
	}
	return false
}

// Mensaje de Director a Mercenario (1)
type Dir_Merc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vivo bool `protobuf:"varint,1,opt,name=vivo,proto3" json:"vivo,omitempty"`
}

func (x *Dir_Merc) Reset() {
	*x = Dir_Merc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_director_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dir_Merc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dir_Merc) ProtoMessage() {}

func (x *Dir_Merc) ProtoReflect() protoreflect.Message {
	mi := &file_director_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dir_Merc.ProtoReflect.Descriptor instead.
func (*Dir_Merc) Descriptor() ([]byte, []int) {
	return file_director_proto_rawDescGZIP(), []int{1}
}

func (x *Dir_Merc) GetVivo() bool {
	if x != nil {
		return x.Vivo
	}
	return false
}

// Mensaje de Mercenario a Director (2)
type Merc_Dir2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
}

func (x *Merc_Dir2) Reset() {
	*x = Merc_Dir2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_director_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Merc_Dir2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Merc_Dir2) ProtoMessage() {}

func (x *Merc_Dir2) ProtoReflect() protoreflect.Message {
	mi := &file_director_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Merc_Dir2.ProtoReflect.Descriptor instead.
func (*Merc_Dir2) Descriptor() ([]byte, []int) {
	return file_director_proto_rawDescGZIP(), []int{2}
}

func (x *Merc_Dir2) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

// Mensaje de Director a Mercenario (2)
type Dir_Merc2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Monto  int32  `protobuf:"varint,2,opt,name=monto,proto3" json:"monto,omitempty"`
}

func (x *Dir_Merc2) Reset() {
	*x = Dir_Merc2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_director_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dir_Merc2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dir_Merc2) ProtoMessage() {}

func (x *Dir_Merc2) ProtoReflect() protoreflect.Message {
	mi := &file_director_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dir_Merc2.ProtoReflect.Descriptor instead.
func (*Dir_Merc2) Descriptor() ([]byte, []int) {
	return file_director_proto_rawDescGZIP(), []int{3}
}

func (x *Dir_Merc2) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Dir_Merc2) GetMonto() int32 {
	if x != nil {
		return x.Monto
	}
	return 0
}

// Mensaje de Director a DoshBank
type Dir_DBank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
}

func (x *Dir_DBank) Reset() {
	*x = Dir_DBank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_director_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dir_DBank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dir_DBank) ProtoMessage() {}

func (x *Dir_DBank) ProtoReflect() protoreflect.Message {
	mi := &file_director_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dir_DBank.ProtoReflect.Descriptor instead.
func (*Dir_DBank) Descriptor() ([]byte, []int) {
	return file_director_proto_rawDescGZIP(), []int{4}
}

func (x *Dir_DBank) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

// Mensaje de DoshBank a Director
type DBank_Dir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Monto  int32  `protobuf:"varint,2,opt,name=monto,proto3" json:"monto,omitempty"`
}

func (x *DBank_Dir) Reset() {
	*x = DBank_Dir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_director_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBank_Dir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBank_Dir) ProtoMessage() {}

func (x *DBank_Dir) ProtoReflect() protoreflect.Message {
	mi := &file_director_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBank_Dir.ProtoReflect.Descriptor instead.
func (*DBank_Dir) Descriptor() ([]byte, []int) {
	return file_director_proto_rawDescGZIP(), []int{5}
}

func (x *DBank_Dir) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *DBank_Dir) GetMonto() int32 {
	if x != nil {
		return x.Monto
	}
	return 0
}

var File_director_proto protoreflect.FileDescriptor

var file_director_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x66, 0x0a, 0x08, 0x4d, 0x65,
	0x72, 0x63, 0x5f, 0x44, 0x69, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x69, 0x73, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x69,
	0x73, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x76, 0x69, 0x76, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x76, 0x69,
	0x76, 0x6f, 0x22, 0x1e, 0x0a, 0x08, 0x44, 0x69, 0x72, 0x5f, 0x4d, 0x65, 0x72, 0x63, 0x12, 0x12,
	0x0a, 0x04, 0x76, 0x69, 0x76, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x76, 0x69,
	0x76, 0x6f, 0x22, 0x23, 0x0a, 0x09, 0x4d, 0x65, 0x72, 0x63, 0x5f, 0x44, 0x69, 0x72, 0x32, 0x12,
	0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x22, 0x39, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x5f, 0x4d,
	0x65, 0x72, 0x63, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x6f, 0x6e, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x6e,
	0x74, 0x6f, 0x22, 0x23, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x5f, 0x44, 0x42, 0x61, 0x6e, 0x6b, 0x12,
	0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x22, 0x39, 0x0a, 0x09, 0x44, 0x42, 0x61, 0x6e, 0x6b,
	0x5f, 0x44, 0x69, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x6f, 0x6e, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x6e,
	0x74, 0x6f, 0x32, 0xb5, 0x01, 0x0a, 0x0c, 0x4b, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x46, 0x6c,
	0x6f, 0x6f, 0x72, 0x12, 0x32, 0x0a, 0x08, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x65, 0x72, 0x63, 0x5f,
	0x44, 0x69, 0x72, 0x1a, 0x12, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44,
	0x69, 0x72, 0x5f, 0x4d, 0x65, 0x72, 0x63, 0x12, 0x3a, 0x0a, 0x0e, 0x4d, 0x65, 0x72, 0x63, 0x5f,
	0x44, 0x69, 0x72, 0x5f, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x12, 0x13, 0x2e, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x65, 0x72, 0x63, 0x5f, 0x44, 0x69, 0x72, 0x32, 0x1a, 0x13,
	0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x69, 0x72, 0x5f, 0x4d, 0x65,
	0x72, 0x63, 0x32, 0x12, 0x35, 0x0a, 0x09, 0x50, 0x65, 0x74, 0x5f, 0x4d, 0x6f, 0x6e, 0x74, 0x6f,
	0x12, 0x13, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x69, 0x72, 0x5f,
	0x44, 0x42, 0x61, 0x6e, 0x6b, 0x1a, 0x13, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x2e, 0x44, 0x42, 0x61, 0x6e, 0x6b, 0x5f, 0x44, 0x69, 0x72, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_director_proto_rawDescOnce sync.Once
	file_director_proto_rawDescData = file_director_proto_rawDesc
)

func file_director_proto_rawDescGZIP() []byte {
	file_director_proto_rawDescOnce.Do(func() {
		file_director_proto_rawDescData = protoimpl.X.CompressGZIP(file_director_proto_rawDescData)
	})
	return file_director_proto_rawDescData
}

var file_director_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_director_proto_goTypes = []interface{}{
	(*Merc_Dir)(nil),  // 0: director.Merc_Dir
	(*Dir_Merc)(nil),  // 1: director.Dir_Merc
	(*Merc_Dir2)(nil), // 2: director.Merc_Dir2
	(*Dir_Merc2)(nil), // 3: director.Dir_Merc2
	(*Dir_DBank)(nil), // 4: director.Dir_DBank
	(*DBank_Dir)(nil), // 5: director.DBank_Dir
}
var file_director_proto_depIdxs = []int32{
	0, // 0: director.KillingFloor.Decision:input_type -> director.Merc_Dir
	2, // 1: director.KillingFloor.Merc_Dir_Monto:input_type -> director.Merc_Dir2
	4, // 2: director.KillingFloor.Pet_Monto:input_type -> director.Dir_DBank
	1, // 3: director.KillingFloor.Decision:output_type -> director.Dir_Merc
	3, // 4: director.KillingFloor.Merc_Dir_Monto:output_type -> director.Dir_Merc2
	5, // 5: director.KillingFloor.Pet_Monto:output_type -> director.DBank_Dir
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_director_proto_init() }
func file_director_proto_init() {
	if File_director_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_director_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Merc_Dir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_director_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dir_Merc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_director_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Merc_Dir2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_director_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dir_Merc2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_director_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dir_DBank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_director_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBank_Dir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_director_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_director_proto_goTypes,
		DependencyIndexes: file_director_proto_depIdxs,
		MessageInfos:      file_director_proto_msgTypes,
	}.Build()
	File_director_proto = out.File
	file_director_proto_rawDesc = nil
	file_director_proto_goTypes = nil
	file_director_proto_depIdxs = nil
}
