// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.0--rc1
// source: proto/ammo.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AmmoClient is the client API for Ammo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AmmoClient interface {
	ReqAmmo(ctx context.Context, in *AmmoReq, opts ...grpc.CallOption) (*AmmoResp, error)
}

type ammoClient struct {
	cc grpc.ClientConnInterface
}

func NewAmmoClient(cc grpc.ClientConnInterface) AmmoClient {
	return &ammoClient{cc}
}

func (c *ammoClient) ReqAmmo(ctx context.Context, in *AmmoReq, opts ...grpc.CallOption) (*AmmoResp, error) {
	out := new(AmmoResp)
	err := c.cc.Invoke(ctx, "/ammo.Ammo/ReqAmmo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AmmoServer is the server API for Ammo service.
// All implementations must embed UnimplementedAmmoServer
// for forward compatibility
type AmmoServer interface {
	ReqAmmo(context.Context, *AmmoReq) (*AmmoResp, error)
	mustEmbedUnimplementedAmmoServer()
}

// UnimplementedAmmoServer must be embedded to have forward compatible implementations.
type UnimplementedAmmoServer struct {
}

func (UnimplementedAmmoServer) ReqAmmo(context.Context, *AmmoReq) (*AmmoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReqAmmo not implemented")
}
func (UnimplementedAmmoServer) mustEmbedUnimplementedAmmoServer() {}

// UnsafeAmmoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AmmoServer will
// result in compilation errors.
type UnsafeAmmoServer interface {
	mustEmbedUnimplementedAmmoServer()
}

func RegisterAmmoServer(s grpc.ServiceRegistrar, srv AmmoServer) {
	s.RegisterService(&Ammo_ServiceDesc, srv)
}

func _Ammo_ReqAmmo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AmmoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmmoServer).ReqAmmo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ammo.Ammo/ReqAmmo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmmoServer).ReqAmmo(ctx, req.(*AmmoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Ammo_ServiceDesc is the grpc.ServiceDesc for Ammo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ammo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ammo.Ammo",
	HandlerType: (*AmmoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReqAmmo",
			Handler:    _Ammo_ReqAmmo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ammo.proto",
}
