// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.0--rc1
// source: proto/ammo.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message to request ammo
type AmmoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Team int32 `protobuf:"varint,1,opt,name=team,proto3" json:"team,omitempty"`
	At   int32 `protobuf:"varint,2,opt,name=at,proto3" json:"at,omitempty"`
	Np   int32 `protobuf:"varint,3,opt,name=np,proto3" json:"np,omitempty"`
}

func (x *AmmoReq) Reset() {
	*x = AmmoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ammo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AmmoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmmoReq) ProtoMessage() {}

func (x *AmmoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ammo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmmoReq.ProtoReflect.Descriptor instead.
func (*AmmoReq) Descriptor() ([]byte, []int) {
	return file_proto_ammo_proto_rawDescGZIP(), []int{0}
}

func (x *AmmoReq) GetTeam() int32 {
	if x != nil {
		return x.Team
	}
	return 0
}

func (x *AmmoReq) GetAt() int32 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *AmmoReq) GetNp() int32 {
	if x != nil {
		return x.Np
	}
	return 0
}

// Message to respond ammo
type AmmoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	App  bool  `protobuf:"varint,1,opt,name=app,proto3" json:"app,omitempty"`
	AvAt int32 `protobuf:"varint,2,opt,name=av_at,json=avAt,proto3" json:"av_at,omitempty"`
	AvNp int32 `protobuf:"varint,3,opt,name=av_np,json=avNp,proto3" json:"av_np,omitempty"`
}

func (x *AmmoResp) Reset() {
	*x = AmmoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ammo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AmmoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmmoResp) ProtoMessage() {}

func (x *AmmoResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ammo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmmoResp.ProtoReflect.Descriptor instead.
func (*AmmoResp) Descriptor() ([]byte, []int) {
	return file_proto_ammo_proto_rawDescGZIP(), []int{1}
}

func (x *AmmoResp) GetApp() bool {
	if x != nil {
		return x.App
	}
	return false
}

func (x *AmmoResp) GetAvAt() int32 {
	if x != nil {
		return x.AvAt
	}
	return 0
}

func (x *AmmoResp) GetAvNp() int32 {
	if x != nil {
		return x.AvNp
	}
	return 0
}

var File_proto_ammo_proto protoreflect.FileDescriptor

var file_proto_ammo_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6d, 0x6d, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x61, 0x6d, 0x6d, 0x6f, 0x22, 0x3d, 0x0a, 0x07, 0x41, 0x6d, 0x6d, 0x6f,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x74, 0x65, 0x61, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x61, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x61, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x6e, 0x70, 0x22, 0x46, 0x0a, 0x08, 0x41, 0x6d, 0x6d, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x03, 0x61, 0x70, 0x70, 0x12, 0x13, 0x0a, 0x05, 0x61, 0x76, 0x5f, 0x61, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x61, 0x76, 0x41, 0x74, 0x12, 0x13, 0x0a, 0x05, 0x61, 0x76,
	0x5f, 0x6e, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x61, 0x76, 0x4e, 0x70, 0x32,
	0x30, 0x0a, 0x04, 0x41, 0x6d, 0x6d, 0x6f, 0x12, 0x28, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x41, 0x6d,
	0x6d, 0x6f, 0x12, 0x0d, 0x2e, 0x61, 0x6d, 0x6d, 0x6f, 0x2e, 0x41, 0x6d, 0x6d, 0x6f, 0x52, 0x65,
	0x71, 0x1a, 0x0e, 0x2e, 0x61, 0x6d, 0x6d, 0x6f, 0x2e, 0x41, 0x6d, 0x6d, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_ammo_proto_rawDescOnce sync.Once
	file_proto_ammo_proto_rawDescData = file_proto_ammo_proto_rawDesc
)

func file_proto_ammo_proto_rawDescGZIP() []byte {
	file_proto_ammo_proto_rawDescOnce.Do(func() {
		file_proto_ammo_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ammo_proto_rawDescData)
	})
	return file_proto_ammo_proto_rawDescData
}

var file_proto_ammo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ammo_proto_goTypes = []interface{}{
	(*AmmoReq)(nil),  // 0: ammo.AmmoReq
	(*AmmoResp)(nil), // 1: ammo.AmmoResp
}
var file_proto_ammo_proto_depIdxs = []int32{
	0, // 0: ammo.Ammo.ReqAmmo:input_type -> ammo.AmmoReq
	1, // 1: ammo.Ammo.ReqAmmo:output_type -> ammo.AmmoResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ammo_proto_init() }
func file_proto_ammo_proto_init() {
	if File_proto_ammo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ammo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AmmoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ammo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AmmoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ammo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ammo_proto_goTypes,
		DependencyIndexes: file_proto_ammo_proto_depIdxs,
		MessageInfos:      file_proto_ammo_proto_msgTypes,
	}.Build()
	File_proto_ammo_proto = out.File
	file_proto_ammo_proto_rawDesc = nil
	file_proto_ammo_proto_goTypes = nil
	file_proto_ammo_proto_depIdxs = nil
}
