// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.0--rc1
// source: proto/director.proto

package Director

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensaje de Mercenario a Director (1)
type Merc_Dir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre   string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Piso     int32  `protobuf:"varint,2,opt,name=piso,proto3" json:"piso,omitempty"`
	Decision int32  `protobuf:"varint,3,opt,name=decision,proto3" json:"decision,omitempty"`
	Vivo     bool   `protobuf:"varint,4,opt,name=vivo,proto3" json:"vivo,omitempty"`
	Aciertos int32  `protobuf:"varint,5,opt,name=aciertos,proto3" json:"aciertos,omitempty"`
}

func (x *Merc_Dir) Reset() {
	*x = Merc_Dir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_director_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Merc_Dir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Merc_Dir) ProtoMessage() {}

func (x *Merc_Dir) ProtoReflect() protoreflect.Message {
	mi := &file_proto_director_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Merc_Dir.ProtoReflect.Descriptor instead.
func (*Merc_Dir) Descriptor() ([]byte, []int) {
	return file_proto_director_proto_rawDescGZIP(), []int{0}
}

func (x *Merc_Dir) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Merc_Dir) GetPiso() int32 {
	if x != nil {
		return x.Piso
	}
	return 0
}

func (x *Merc_Dir) GetDecision() int32 {
	if x != nil {
		return x.Decision
	}
	return 0
}

func (x *Merc_Dir) GetVivo() bool {
	if x != nil {
		return x.Vivo
	}
	return false
}

func (x *Merc_Dir) GetAciertos() int32 {
	if x != nil {
		return x.Aciertos
	}
	return 0
}

// Mensaje de Director a Mercenario (1)
type Dir_Merc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vivo     bool  `protobuf:"varint,1,opt,name=vivo,proto3" json:"vivo,omitempty"`
	Aciertos int32 `protobuf:"varint,2,opt,name=aciertos,proto3" json:"aciertos,omitempty"`
}

func (x *Dir_Merc) Reset() {
	*x = Dir_Merc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_director_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dir_Merc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dir_Merc) ProtoMessage() {}

func (x *Dir_Merc) ProtoReflect() protoreflect.Message {
	mi := &file_proto_director_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dir_Merc.ProtoReflect.Descriptor instead.
func (*Dir_Merc) Descriptor() ([]byte, []int) {
	return file_proto_director_proto_rawDescGZIP(), []int{1}
}

func (x *Dir_Merc) GetVivo() bool {
	if x != nil {
		return x.Vivo
	}
	return false
}

func (x *Dir_Merc) GetAciertos() int32 {
	if x != nil {
		return x.Aciertos
	}
	return 0
}

// Mensaje de Mercenario a Director (2)
type Merc_Dir2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
}

func (x *Merc_Dir2) Reset() {
	*x = Merc_Dir2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_director_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Merc_Dir2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Merc_Dir2) ProtoMessage() {}

func (x *Merc_Dir2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_director_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Merc_Dir2.ProtoReflect.Descriptor instead.
func (*Merc_Dir2) Descriptor() ([]byte, []int) {
	return file_proto_director_proto_rawDescGZIP(), []int{2}
}

func (x *Merc_Dir2) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

// Mensaje de Director a Mercenario (2)
type Dir_Merc2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Monto  int32  `protobuf:"varint,2,opt,name=monto,proto3" json:"monto,omitempty"`
}

func (x *Dir_Merc2) Reset() {
	*x = Dir_Merc2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_director_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dir_Merc2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dir_Merc2) ProtoMessage() {}

func (x *Dir_Merc2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_director_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dir_Merc2.ProtoReflect.Descriptor instead.
func (*Dir_Merc2) Descriptor() ([]byte, []int) {
	return file_proto_director_proto_rawDescGZIP(), []int{3}
}

func (x *Dir_Merc2) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Dir_Merc2) GetMonto() int32 {
	if x != nil {
		return x.Monto
	}
	return 0
}

// Mensaje de Director a DoshBank (1)
type Dir_DBank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
}

func (x *Dir_DBank) Reset() {
	*x = Dir_DBank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_director_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dir_DBank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dir_DBank) ProtoMessage() {}

func (x *Dir_DBank) ProtoReflect() protoreflect.Message {
	mi := &file_proto_director_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dir_DBank.ProtoReflect.Descriptor instead.
func (*Dir_DBank) Descriptor() ([]byte, []int) {
	return file_proto_director_proto_rawDescGZIP(), []int{4}
}

func (x *Dir_DBank) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

// Mensaje de DoshBank a Director (1)
type DBank_Dir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Monto  int32  `protobuf:"varint,2,opt,name=monto,proto3" json:"monto,omitempty"`
}

func (x *DBank_Dir) Reset() {
	*x = DBank_Dir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_director_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBank_Dir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBank_Dir) ProtoMessage() {}

func (x *DBank_Dir) ProtoReflect() protoreflect.Message {
	mi := &file_proto_director_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBank_Dir.ProtoReflect.Descriptor instead.
func (*DBank_Dir) Descriptor() ([]byte, []int) {
	return file_proto_director_proto_rawDescGZIP(), []int{5}
}

func (x *DBank_Dir) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *DBank_Dir) GetMonto() int32 {
	if x != nil {
		return x.Monto
	}
	return 0
}

// Mensaje director a NameNode (1)
type Dir_NameNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre   string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Piso     int32  `protobuf:"varint,2,opt,name=piso,proto3" json:"piso,omitempty"`
	Decision int32  `protobuf:"varint,3,opt,name=decision,proto3" json:"decision,omitempty"`
}

func (x *Dir_NameNode) Reset() {
	*x = Dir_NameNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_director_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dir_NameNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dir_NameNode) ProtoMessage() {}

func (x *Dir_NameNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_director_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dir_NameNode.ProtoReflect.Descriptor instead.
func (*Dir_NameNode) Descriptor() ([]byte, []int) {
	return file_proto_director_proto_rawDescGZIP(), []int{6}
}

func (x *Dir_NameNode) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Dir_NameNode) GetPiso() int32 {
	if x != nil {
		return x.Piso
	}
	return 0
}

func (x *Dir_NameNode) GetDecision() int32 {
	if x != nil {
		return x.Decision
	}
	return 0
}

// Mensaje NameNode a Director (1)
type NameNode_Dir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack int32 `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (x *NameNode_Dir) Reset() {
	*x = NameNode_Dir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_director_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameNode_Dir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameNode_Dir) ProtoMessage() {}

func (x *NameNode_Dir) ProtoReflect() protoreflect.Message {
	mi := &file_proto_director_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameNode_Dir.ProtoReflect.Descriptor instead.
func (*NameNode_Dir) Descriptor() ([]byte, []int) {
	return file_proto_director_proto_rawDescGZIP(), []int{7}
}

func (x *NameNode_Dir) GetAck() int32 {
	if x != nil {
		return x.Ack
	}
	return 0
}

// Mensaje NameNode a DataNode (1)
type NameNode_DataNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre   string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Piso     int32  `protobuf:"varint,2,opt,name=piso,proto3" json:"piso,omitempty"`
	Decision int32  `protobuf:"varint,3,opt,name=decision,proto3" json:"decision,omitempty"`
}

func (x *NameNode_DataNode) Reset() {
	*x = NameNode_DataNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_director_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameNode_DataNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameNode_DataNode) ProtoMessage() {}

func (x *NameNode_DataNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_director_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameNode_DataNode.ProtoReflect.Descriptor instead.
func (*NameNode_DataNode) Descriptor() ([]byte, []int) {
	return file_proto_director_proto_rawDescGZIP(), []int{8}
}

func (x *NameNode_DataNode) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *NameNode_DataNode) GetPiso() int32 {
	if x != nil {
		return x.Piso
	}
	return 0
}

func (x *NameNode_DataNode) GetDecision() int32 {
	if x != nil {
		return x.Decision
	}
	return 0
}

// Mensaje DataNode a NameNode (1)
type DataNode_NameNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack int32 `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (x *DataNode_NameNode) Reset() {
	*x = DataNode_NameNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_director_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataNode_NameNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataNode_NameNode) ProtoMessage() {}

func (x *DataNode_NameNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_director_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataNode_NameNode.ProtoReflect.Descriptor instead.
func (*DataNode_NameNode) Descriptor() ([]byte, []int) {
	return file_proto_director_proto_rawDescGZIP(), []int{9}
}

func (x *DataNode_NameNode) GetAck() int32 {
	if x != nil {
		return x.Ack
	}
	return 0
}

var File_proto_director_proto protoreflect.FileDescriptor

var file_proto_director_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x22, 0x82, 0x01, 0x0a, 0x08, 0x4d, 0x65, 0x72, 0x63, 0x5f, 0x44, 0x69, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e,
	0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x69, 0x73, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x69, 0x73, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x63,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x65, 0x63,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x69, 0x76, 0x6f, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x04, 0x76, 0x69, 0x76, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x69,
	0x65, 0x72, 0x74, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x63, 0x69,
	0x65, 0x72, 0x74, 0x6f, 0x73, 0x22, 0x3a, 0x0a, 0x08, 0x44, 0x69, 0x72, 0x5f, 0x4d, 0x65, 0x72,
	0x63, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x69, 0x76, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x76, 0x69, 0x76, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x69, 0x65, 0x72, 0x74, 0x6f,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x63, 0x69, 0x65, 0x72, 0x74, 0x6f,
	0x73, 0x22, 0x23, 0x0a, 0x09, 0x4d, 0x65, 0x72, 0x63, 0x5f, 0x44, 0x69, 0x72, 0x32, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x22, 0x39, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x5f, 0x4d, 0x65,
	0x72, 0x63, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d,
	0x6f, 0x6e, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74,
	0x6f, 0x22, 0x23, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x5f, 0x44, 0x42, 0x61, 0x6e, 0x6b, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x22, 0x39, 0x0a, 0x09, 0x44, 0x42, 0x61, 0x6e, 0x6b, 0x5f,
	0x44, 0x69, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d,
	0x6f, 0x6e, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74,
	0x6f, 0x22, 0x56, 0x0a, 0x0c, 0x44, 0x69, 0x72, 0x5f, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x69, 0x73,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x69, 0x73, 0x6f, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x20, 0x0a, 0x0c, 0x4e, 0x61, 0x6d,
	0x65, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x44, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x22, 0x5b, 0x0a, 0x11, 0x4e,
	0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x69, 0x73, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x69, 0x73, 0x6f, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x25, 0x0a, 0x11, 0x44, 0x61, 0x74, 0x61,
	0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x32,
	0xbc, 0x02, 0x0a, 0x0c, 0x4b, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x46, 0x6c, 0x6f, 0x6f, 0x72,
	0x12, 0x32, 0x0a, 0x08, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x2e, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x65, 0x72, 0x63, 0x5f, 0x44, 0x69, 0x72,
	0x1a, 0x12, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x69, 0x72, 0x5f,
	0x4d, 0x65, 0x72, 0x63, 0x12, 0x3a, 0x0a, 0x0e, 0x4d, 0x65, 0x72, 0x63, 0x5f, 0x44, 0x69, 0x72,
	0x5f, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x12, 0x13, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x4d, 0x65, 0x72, 0x63, 0x5f, 0x44, 0x69, 0x72, 0x32, 0x1a, 0x13, 0x2e, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x69, 0x72, 0x5f, 0x4d, 0x65, 0x72, 0x63, 0x32,
	0x12, 0x35, 0x0a, 0x09, 0x50, 0x65, 0x74, 0x5f, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x12, 0x13, 0x2e,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x69, 0x72, 0x5f, 0x44, 0x42, 0x61,
	0x6e, 0x6b, 0x1a, 0x13, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x42,
	0x61, 0x6e, 0x6b, 0x5f, 0x44, 0x69, 0x72, 0x12, 0x3c, 0x0a, 0x0a, 0x44, 0x69, 0x72, 0x5f, 0x4e,
	0x4e, 0x5f, 0x44, 0x65, 0x63, 0x12, 0x16, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x2e, 0x44, 0x69, 0x72, 0x5f, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x1a, 0x16, 0x2e,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64,
	0x65, 0x5f, 0x44, 0x69, 0x72, 0x12, 0x47, 0x0a, 0x0b, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64,
	0x65, 0x5f, 0x44, 0x4e, 0x12, 0x1b, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e,
	0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64,
	0x65, 0x1a, 0x1b, 0x2e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x4e, 0x6f, 0x64, 0x65, 0x5f, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x42, 0x0c,
	0x5a, 0x0a, 0x2e, 0x2f, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_director_proto_rawDescOnce sync.Once
	file_proto_director_proto_rawDescData = file_proto_director_proto_rawDesc
)

func file_proto_director_proto_rawDescGZIP() []byte {
	file_proto_director_proto_rawDescOnce.Do(func() {
		file_proto_director_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_director_proto_rawDescData)
	})
	return file_proto_director_proto_rawDescData
}

var file_proto_director_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_director_proto_goTypes = []interface{}{
	(*Merc_Dir)(nil),          // 0: director.Merc_Dir
	(*Dir_Merc)(nil),          // 1: director.Dir_Merc
	(*Merc_Dir2)(nil),         // 2: director.Merc_Dir2
	(*Dir_Merc2)(nil),         // 3: director.Dir_Merc2
	(*Dir_DBank)(nil),         // 4: director.Dir_DBank
	(*DBank_Dir)(nil),         // 5: director.DBank_Dir
	(*Dir_NameNode)(nil),      // 6: director.Dir_NameNode
	(*NameNode_Dir)(nil),      // 7: director.NameNode_Dir
	(*NameNode_DataNode)(nil), // 8: director.NameNode_DataNode
	(*DataNode_NameNode)(nil), // 9: director.DataNode_NameNode
}
var file_proto_director_proto_depIdxs = []int32{
	0, // 0: director.KillingFloor.Decision:input_type -> director.Merc_Dir
	2, // 1: director.KillingFloor.Merc_Dir_Monto:input_type -> director.Merc_Dir2
	4, // 2: director.KillingFloor.Pet_Monto:input_type -> director.Dir_DBank
	6, // 3: director.KillingFloor.Dir_NN_Dec:input_type -> director.Dir_NameNode
	8, // 4: director.KillingFloor.NameNode_DN:input_type -> director.NameNode_DataNode
	1, // 5: director.KillingFloor.Decision:output_type -> director.Dir_Merc
	3, // 6: director.KillingFloor.Merc_Dir_Monto:output_type -> director.Dir_Merc2
	5, // 7: director.KillingFloor.Pet_Monto:output_type -> director.DBank_Dir
	7, // 8: director.KillingFloor.Dir_NN_Dec:output_type -> director.NameNode_Dir
	9, // 9: director.KillingFloor.NameNode_DN:output_type -> director.DataNode_NameNode
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_director_proto_init() }
func file_proto_director_proto_init() {
	if File_proto_director_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_director_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Merc_Dir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_director_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dir_Merc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_director_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Merc_Dir2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_director_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dir_Merc2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_director_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dir_DBank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_director_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBank_Dir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_director_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dir_NameNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_director_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameNode_Dir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_director_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameNode_DataNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_director_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataNode_NameNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_director_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_director_proto_goTypes,
		DependencyIndexes: file_proto_director_proto_depIdxs,
		MessageInfos:      file_proto_director_proto_msgTypes,
	}.Build()
	File_proto_director_proto = out.File
	file_proto_director_proto_rawDesc = nil
	file_proto_director_proto_goTypes = nil
	file_proto_director_proto_depIdxs = nil
}
