// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.0--rc1
// source: proto/mercenary_namenode.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MercenaryTaskServiceClient is the client API for MercenaryTaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MercenaryTaskServiceClient interface {
	SendTask(ctx context.Context, in *MercenaryTask, opts ...grpc.CallOption) (*MercenaryTaskAck, error)
}

type mercenaryTaskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMercenaryTaskServiceClient(cc grpc.ClientConnInterface) MercenaryTaskServiceClient {
	return &mercenaryTaskServiceClient{cc}
}

func (c *mercenaryTaskServiceClient) SendTask(ctx context.Context, in *MercenaryTask, opts ...grpc.CallOption) (*MercenaryTaskAck, error) {
	out := new(MercenaryTaskAck)
	err := c.cc.Invoke(ctx, "/namenode.MercenaryTaskService/SendTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MercenaryTaskServiceServer is the server API for MercenaryTaskService service.
// All implementations must embed UnimplementedMercenaryTaskServiceServer
// for forward compatibility
type MercenaryTaskServiceServer interface {
	SendTask(context.Context, *MercenaryTask) (*MercenaryTaskAck, error)
	mustEmbedUnimplementedMercenaryTaskServiceServer()
}

// UnimplementedMercenaryTaskServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMercenaryTaskServiceServer struct {
}

func (UnimplementedMercenaryTaskServiceServer) SendTask(context.Context, *MercenaryTask) (*MercenaryTaskAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTask not implemented")
}
func (UnimplementedMercenaryTaskServiceServer) mustEmbedUnimplementedMercenaryTaskServiceServer() {}

// UnsafeMercenaryTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MercenaryTaskServiceServer will
// result in compilation errors.
type UnsafeMercenaryTaskServiceServer interface {
	mustEmbedUnimplementedMercenaryTaskServiceServer()
}

func RegisterMercenaryTaskServiceServer(s grpc.ServiceRegistrar, srv MercenaryTaskServiceServer) {
	s.RegisterService(&MercenaryTaskService_ServiceDesc, srv)
}

func _MercenaryTaskService_SendTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MercenaryTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MercenaryTaskServiceServer).SendTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/namenode.MercenaryTaskService/SendTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MercenaryTaskServiceServer).SendTask(ctx, req.(*MercenaryTask))
	}
	return interceptor(ctx, in, info, handler)
}

// MercenaryTaskService_ServiceDesc is the grpc.ServiceDesc for MercenaryTaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MercenaryTaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "namenode.MercenaryTaskService",
	HandlerType: (*MercenaryTaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTask",
			Handler:    _MercenaryTaskService_SendTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mercenary_namenode.proto",
}
